#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd) # get the script dir
dry="1"

# i want to run dry by default
while [[ $# > 0 ]]; do
    if [[ $1 == "--run" ]]; then
        dry="0"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then # if we have a dry run
        echo "[DRY_RUN]: $@" # log everything with indication that it's a dry run
    else
        echo "$@" # otherwise log everything
    fi
}

execute() {
    log "execute $@"
    if [[ $dry == "1" ]]; then # if we have a dry run
        return # don't run the scripts
    fi
    "$@" # otherwise run them
}

log "------------ dev-env ------------"

copy_dir() {
    from=$1
    to=$2

    pushd $from > /dev/null # we don't want the output

    dirs=$(find . -mindepth 1 maxdepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir

    done

    popd > /dev/null # we don't want the output
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)

    execute rm $to/$name
    execute cp -r $from $to/$name
}
