#!/usr/bin/env bash
set -e # stops the script if anything fails

# nvim
sudo dnf install neovim

# tmux
sudo dnf install tmux

# zsh
sudo dnf install zsh
zsh --version
sudo chsh $USER
echo $SHELL

# oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# ghostty
sudo dnf install git gcc make SDL2-devel fontconfig-devel pango-devel
sudo dnf install golang

git clone git@github.com:ghostty-org/ghostty.git
cd ghostty
make

sudo cp ghostty /usr/local/bin/

ghostty --version # just for confirmation



