#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd) # get the script dir
dry="0"

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then # if we have a dry run
        echo "[DRY_RUN]: $@" # log everything with indication that it's a dry run
    else
        echo "$@" # otherwise log everything
    fi
}

execute() {
    log "execute $@"
    if [[ $dry == "1" ]]; then # if we have a dry run
        return # don't run the scripts
    fi
    "$@" # otherwise run them
}

log "------------ dev-env ------------"

copy_dir() {
    from=$1
    to=$2

    pushd $from > /dev/null # we don't want the output

    dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done

    popd > /dev/null # we don't want the output
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)

    execute rm $to/$name
    execute cp -r $from $to/$name
}

# root files
root_files=(".zshrc" ".zsh_profile" ".tmux.conf" ".gitconfig")
for file in "${root_files[@]}"; do
    copy_file env/"$file" "$HOME"
done

# .config
copy_dir env/.config $HOME/.config

# scripts
cd $script_dir
scripts=$(find env/scripts -maxdepth 1 -mindepth 1 -executable -type f)

for script in $scripts; do
    copy_file "$script" "$HOME/.local/bin"
done

