#!/usr/bin/env bash

actions=("suspend" "sleep" "shutdown" "reboot" "hibernate")

chosen=$(printf "%s\n" "${actions[@]}" | rofi -dmenu -p "Select action:")

if [ -n "$chosen" ]; then
    systemctl "$chosen"
fi
